source 'https://rubygems.org'

gem 'sinatra', '~> 1.4.5'
gem 'rack', '~> 1.5.2'
gem 'omniauth-rdio', '~> 0.1.0'
gem 'rdio-ruby', git: 'https://github.com/nixme/rdio-ruby.git'
gem 'json', '~> 1.8.1'
gem 'multi_json', '~> 1.10.1'
gem 'puma', '~> 2.9.0'
gem 'foreman', '~> 0.74.0'
